import BP1 from "../../src/resources/img/bird/avione-lorikeets-wild-bird-nectar,500g.png"
import BP2 from "../../src/resources/img/bird/barastoc-3-grain-scratch-mix,20kg.png"
import BP3 from "../../src/resources/img/bird/harmony-wild-bird-mix,8kg.png"
import BP4 from "../../src/resources/img/bird/barastoc-chick-starter,20kg.png"
import BP5 from "../../src/resources/img/bird/country-heritage-organic-backyard-layer-pellets,20kg.png"
import BP6 from "../../src/resources/img/bird/golden-cob-budgie-mix,5kg.png"
import BP7 from "../../src/resources/img/bird/barastoc-champion-layer-premium-pellets,20kg.png"
import BP8 from "../../src/resources/img/bird/laucke-red-hen-free-range,20kg.png"
import BP9 from "../../src/resources/img/bird/mc-mahon-and-sons-shell-grit-fine,5kg.png"
import BP10 from "../../src/resources/img/bird/peckish-chicken-free-range-layer-pellets,18kg.png"
import BP11 from "../../src/resources/img/bird/laucke-red-hen-layer,20kg.png"
import BP12 from "../../src/resources/img/bird/peters-wild-bird-seed-large-birds,1.5kg.png"
import BP13 from "../../src/resources/img/bird/trill-budgie-mix,1.8kg.png"
import BP14 from "../../src/resources/img/bird/vella-chicken-and-duckling-starter-crumble,18kg.png"
import BP15 from "../../src/resources/img/bird/vetafarm-bird-neocare,450g.png"
import BP16 from "../../src/resources/img/bird/whistler-poultry-calcium-grit-tub,3.5kg.png"
import BP17 from "../../src/resources/img/bird/vetafarm-bird-nutriblend-pellets-mini,2kg.png"
import BP18 from "../../src/resources/img/bird/vetafarm-parrot-breeder-pellets,2kg.png"
import BP19 from "../../src/resources/img/bird/vetafarm-paradise-pellets,2kg.png"
import BP20 from "../../src/resources/img/bird/barastoc-pullet-grower,20kg.png"
import BP21 from "../../src/resources/img/bird/vella-free-range-layer-pellet,20kg.png"
import BP22 from "../../src/resources/img/bird/vetafarm-parrot-pellet-maintenance,2kg.png"
import BP23 from "../../src/resources/img/bird/wombaroo-lori-and-honeyeater-food,300kg.png"
import BP24 from "../../src/resources/img/bird/trill-parrot-mix,10kg.png"
import BP25 from "../../src/resources/img/bird/vetafarm-parrot-essentials-food,2kg.png"
import BP26 from "../../src/resources/img/bird/laucke-showbird-breeder-mp,20kg.png"
import BP27 from "../../src/resources/img/bird/barastoc-darling-downs-layer,20kg.png"






export const BirdVarietyList = [
    {name: 'Buggle Food', count: 1, key: 0},
    {name: 'Chicken Food', count: 2, key: 1},
    {name: 'Cocktael Food', count: 3, key: 2},
    {name: 'Finch and Canary Food', count: 4, key: 3},
    {name: 'Lorikeet Food', count: 5, key: 4},
    {name: 'Parrot Food', count: 6, key: 5},
    {name: 'Wold Bird Food', count: 7, key: 6},
    {name: 'Duck Food', count: 8, key: 7},
    {name: 'Other Bird Food', count: 9, key: 8},
]

export const BirdTypeList = [
    {name: 'Crumbles', count: 1, key: 0},
    {name: 'Grit', count: 2, key: 1},
    {name: 'Nectar', count: 3, key: 2},
    {name: 'Pellets', count: 4, key: 3},
    {name: 'Seed and Grain Mix', count: 5, key: 4},
    {name: 'Seed and Grain Mixes', count: 6, key: 7},
    {name: 'Formula', count: 7, key: 8},
//Type
]

export const BirdBreedList = [
    {name: 'Budgie', count: 1, key: 0},
    {name: 'Canary', count: 2, key: 1},
    {name: 'Chickens', count: 3, key: 2},
    {name: 'Cocktaiel', count: 4, key: 3},
    {name: 'Ducks', count: 5, key: 4},
    {name: 'Parrot', count: 6, key: 5},
    {name: 'Pigeon', count: 7, key: 6},
    {name: 'Wild Bird', count: 8, key: 7},
//Feature
]


export const BirdBrandList = [
    {name: 'avione', count: 1, key: 0},
    {name: 'barastoc', count: 2, key: 1},
    {name: 'harmony', count: 3, key: 2},
    {name: 'country', count: 4, key: 3},
    {name: 'golden', count: 5, key: 4},
    {name: 'laucke', count: 6, key: 5},
    {name: 'Peters', count: 7, key: 6},
    {name: 'trill', count: 8, key: 7},
    {name: 'vetafarm', count: 9, key: 8},
    {name: 'whistler', count: 9, key: 8},
    {name: 'wombaroo', count: 9, key: 8},

]


export const BirdProductList = [
    {
        Product:1,
        source: BP1,
        title: 'AVIONE',
        subTitle: 'Lorikeets Wild Bird Nectar, 500G',
        star: 5,
        review: 83,
        mount: '500g',
        mount2: '1kg',
        price: 11.65,
        state: 'none',
        variety : 'Buggle Food',
        type : 'Crumbles',
        Breed : 'Budgie',
        brand : 'avione',
    },
    {
        Product:2,
        source: BP2,
        title: 'BARASTOC',
        subTitle: '3Grain Scratch Mix,20kg.',
        star: 5,
        review: 138,
        mount: '1kg',
        mount2: '3kg',
        price: 15.00,
        state: 'none',
        variety : 'Chicken Food',
        type : 'Grit',
        Breed : 'Canary',
        brand : 'Barastoc',

    },
    {
        Product:3,
        source: BP3,
        title: 'HARMONY',
        subTitle: 'Wild Bird Mix,8kg',
        star: 5,
        review: 11,
        mount: '320g',
        price: 9.40,
        state: 'none',
        variety : 'Cocktael Food',
        type : 'Seed and Grain Mix',
        Breed : 'Cocktaiel',
        brand : 'Harmony',

    },
    {
        Product:4,
        source: BP4,
        title: 'BARASTOC',
        subTitle: 'Chick Starter,20kg',
        star: 4,
        review: 49,
        mount: '10kg',
        mount2: '20kg',
        price: 37.50,
        state: 'none',
        variety : 'Chicken Food',
        type : 'Pellets',
        Breed : 'Wild Bird',
        brand : 'Barastoc',

    },
    {
        Product:5,
        source: BP5,
        title: 'COUNTRY',
        subTitle: 'Heritage Organic Backyard Layer Pellets,20kg',
        star: 5,
        review: 25,
        mount: '20kg',
        mount2: '25kg',
        price: 53.59,
        state: 'none',
        variety : 'Lorikeet Food',
        type : 'Seed and Grain Mixes',
        Breed : 'Pigeon',
        brand : 'Country',

    },
    {
        Product:6,
        source: BP6,
        title: 'GOLDEN',
        subTitle: 'Cob Budgie Mix,5kg',
        star: 5,
        review: 1,
        mount: '5kg',
        price: 18.85,
        state: 'none',
        variety : 'Duck Food',
        type : 'Formula',
        Breed : 'Parrot',
        brand : 'Golden',

    },
    {
        Product:7,
        source: BP7,
        title: 'BARASTOC',
        subTitle: 'Champion Layer Premium Pellets,20kg',
        star: 4,
        review: 26,
        mount: '20kg',
        mount2: '22kg',
        price: 34.56,
        state: 'none',
        variety : 'Other Bird Food',
        type : 'Grit',
        Breed : 'Ducks',
        brand : 'Barastoc',

    },
    {
        Product:8,
        source: BP8,
        title: 'LAUCKE',
        subTitle: 'Red Hen Free Range,20kg',
        star: 5,
        review: 19,
        mount: '20kg',
        mount2: '30kg',
        price: 33.00,
        state: 'none',
        variety : 'Lorikeet Food',
        type : 'Crumbles',
        Breed : 'Budgie',
        brand : 'Laucke',

    },
    {
        Product:9,
        source: BP9,
        title: 'MC',
        subTitle: 'Mahon And Sons Shell Grit Fine,5kg',
        star: 5,
        review: 11,
        mount: '5kg',
        mount2: '8kg',
        price: 19.95,
        state: 'none',
        variety : 'Parrot Food',
        type : 'Crumbles',
        Breed : 'Nectar',
        brand : 'Mc',

    },
    {
        Product:10,
        source: BP10,
        title: 'PECKISH',
        subTitle: 'Chicken Free Range Layer Pellets,18kg',
        star: 5,
        review: 2,
        mount: '18kg',
        mount2: '25kg',
        price: 33.25,
        state: 'none',
        variety : 'Wold Bird Food',
        type : 'Grit',
        Breed : 'Budgie',
        brand : 'Canary',

    },
    {
        Product:11,
        source: BP11,
        title: 'LAUCKE',
        subTitle: 'Red Hen Layer,20kg',
        star: 5,
        review: 89,
        mount: '20kg',
        mount2: '40kg',
        price: 62.34,
        state: 'none',
        variety : 'Finch and Canary Food',
        type : 'Seed and Grain Mix',
        Breed : 'Budgie',
        brand : 'Laucke',

    },
    {
        Product:12,
        source: BP12,
        title: 'PETERS',
        subTitle: 'Wild Bird Seed Large Birds,1.5kg',
        star: 4,
        review: 36,
        mount: '1.5kg',
        mount2: '6kg',
        price: 11.99,
        state: 'none',
        variety : 'Lorikeet Food',
        type : 'Nectar',
        Breed : 'Chickens',
        brand : 'Peters',

    },
    {
        Product:13,
        source: BP13,
        title: 'TRILL',
        subTitle: 'Budgie Mix,1.8kg',
        star: 4,
        review: 7,
        mount: '1.8kg',
        mount2: '5kg',
        price: 8.95,
        state: 'none',
        variety : 'Other Bird Food',
        type : 'Nectar',
        Breed : 'Budgie',
        brand : 'Trill',

    },
    {
        Product:14,
        source: BP14,
        title: 'VELLA',
        subTitle: 'Chicken And Duckling Starter Crumble,18kg',
        star: 5,
        review: 15,
        mount: '18kg',
        mount2: '30kg',
        price: 45.60,
        state: 'Sold Out',
        variety : 'Cocktael Food',
        type : 'Seed and Grain Mix',
        Breed : 'Canary',
        brand : 'Vella',

    },
    {
        Product:15,
        source: BP15,
        title: 'VETAFARM',
        subTitle: 'Bird Neocare,450g',
        star: 5,
        review: 3,
        mount: '450g',
        price: 8.84,
        state: 'none',
        variety : 'Parrot Food',
        type : 'Pellets',
        Breed : 'Parrot',
        brand : 'Vetafarm',

    },
    {
        Product:16,
        source: BP16,
        title: 'WHISTLER',
        subTitle: 'Poultry Calcium Grit Tub,3.5kg',
        star: 4,
        review: 5,
        mount: '350g',
        mount2: '1kg',
        price: 7.99,
        state: 'none',
        variety : 'Buggle Food',
        type : 'Grit',
        Breed : 'Budgie',
        brand : 'Whistler',

    },
    {
        Product:17,
        source: BP17,
        title: 'VETAFARM',
        subTitle: 'Bird Neocare,450g',
        star: 5,
        review: 71,
        mount: '450g',
        mount2: '1kg',
        price: 11.99,
        state: 'none',
        variety : 'Duck Food',
        type : 'Seed and Grain Mixes',
        Breed : 'Pigeon',
        brand : 'Vetafarm',

    },
    {
        Product:18,
        source: BP18,
        title: 'VETAFARM',
        subTitle: 'Parrot Breeder Pellets,2kg',
        star: 4,
        review: 17,
        mount: '2kg',
        mount2: '5kg',
        price: 27.50,
        state: 'none',
        variety : 'Parrot Food',
        type : 'Seed and Grain Mixes',
        Breed : 'Parrot',
        brand : 'Vetafarm',
    },
    {
        Product:19,
        source: BP19,
        title: 'VETAFARM',
        subTitle: 'Paradise Pellets,2kg',
        star: 5,
        review: 53,
        mount: '2kg',
        mount2: '4kg',
        price: 26.12,
        state: 'none',
        variety : 'Duck Food',
        type : 'Crumbles',
        Breed : 'Wild Bird',
        brand : 'Vetafarm',

    },
    {
        Product:20,
        source: BP20,
        title: 'BARASTOC',
        subTitle: 'Pullet Grower,20kg',
        star: 4,
        review: 28,
        mount: '20kg',
        mount2: '30kg',
        price: 49.75,
        state: 'none',
        variety : 'Other Bird Food',
        type : 'Formula',
        Breed : 'Wild Bird',
        brand : 'Barastoc',

    },
    {
        Product:21,
        source: BP21,
        title: 'VELLA',
        subTitle: 'Free Range Layer Pellet,20kg',
        star: 5,
        review: 71,
        mount: '20kg',
        mount2: '30kg',
        price: 64.95,
        state: 'none',
        variety : 'Lorikeet Food',
        type : 'Crumbles',
        Breed : 'Canary',
        brand : 'Vella',

    },
    {
        Product:22,
        source: BP22,
        title: 'VETAFARM',
        subTitle: 'Parrot Pellet Maintenance,2kg',
        star: 5,
        review: 10,
        mount: '2kg',
        mount2: '4kg',
        price: 33.13,
        state: 'none',
        variety : 'Chicken Food',
        type : 'Pellets',
        Breed : 'Chickens',
        brand : 'Vetafarm',

    },
    {
        Product:23,
        source: BP23,
        title: 'WOMBAROO',
        subTitle: 'Lori And Honeyeater Food,300g',
        star: 5,
        review: 5,
        mount: '300g',
        mount2: '1kg',
        price: 12.24,
        state: 'none',
        variety : 'Finch and Canary Food',
        type : 'Grit',
        Breed : 'Budgie',
        brand : 'Wombaroo',

    },
    {
        Product:24,
        source: BP24,
        title: 'TRILL',
        subTitle: 'Parrot Mix,10kg',
        star: 5,
        review: 77,
        mount: '10kg',
        mount2: '15kg',
        price: 24.40,
        state: 'none',
        variety : 'Parrot Food',
        type : 'Seed and Grain Mix',
        Breed : 'Parrot',
        brand : 'Trill',

    },
    {
        Product:25,
        source: BP25,
        title: 'VETAFARM',
        subTitle: 'Parrot Essentials Food,2kg',
        star: 5,
        review: 77,
        mount: '2kg',
        mount2: '6kg',
        price: 34.40,
        state: 'none',
        variety : 'Wold Bird Food',
        type : 'Crumbles',
        Breed : 'Pigeon',
        brand : 'Vetafarm',

    },
    {
        Product:26,
        source: BP26,
        title: 'LAUCKE',
        subTitle: 'Showbird Breeder Mp,20kg',
        star: 4,
        review: 10,
        mount: '20Kg',
        mount2: '30kg',
        price: 55.19,
        state: 'none',
        variety : 'Lorikeet Food',
        type : 'Seed and Grain Mixes',
        Breed : 'Budgie',
        brand : 'Laucke',

    },
    {
        product:27,
        source: BP27,
        title: 'BARASTOC',
        subTitle: 'Seed and Grain Mixes.500g',
        star: 5,
        review: 73,
        mount: '500g',
        mount2: '3kg',
        price: 11.50,
        state: 'none',
        variety : 'Duck Food',
        type : 'Pellets',
        Breed : 'Ducks',
        brand : 'Barastoc',

    },
]
