import CP1 from "../../src/resources/img/cat/Advance1.png"
import CP2 from "../../src/resources/img/cat/BlackHawk1.png"
import CP3 from "../../src/resources/img/cat/FelineNatural.png"
import CP4 from "../../src/resources/img/cat/HealthyEverydayPets1.png"
import CP5 from "../../src/resources/img/cat/HillsScienceDiet1.png"
import CP6 from "../../src/resources/img/cat/IvoryCoat.png"
import CP7 from "../../src/resources/img/cat/MealsForMeows.png"
import CP8 from "../../src/resources/img/cat/OpenFarm1.png"
import CP9 from "../../src/resources/img/cat/Orijen1.png"
import CP10 from "../../src/resources/img/cat/ProPlan.png"
import CP11 from "../../src/resources/img/cat/RoyalCanin1.png"
import CP12 from "../../src/resources/img/cat/TasteofWild.png"
import CP13 from "../../src/resources/img/cat/Vetalogica1.png"
import CP14 from "../../src/resources/img/cat/Wellness.png"
import CP15 from "../../src/resources/img/cat/Whiskas.png"
import CP16 from "../../src/resources/img/cat/Ziwi1.png"
import CP17 from "../../src/resources/img/cat/Advance2.png"
import CP18 from "../../src/resources/img/cat/HealthyEverydayPets2.png"
import CP19 from "../../src/resources/img/cat/HillsScienceDiet2.png"
import CP20 from "../../src/resources/img/cat/MealsForMeows2.png"
import CP21 from "../../src/resources/img/cat/Orijen2.png"
import CP22 from "../../src/resources/img/cat/RoyalCanin2.png"
import CP23 from "../../src/resources/img/cat/Ziwi2.png"
import CP24 from "../../src/resources/img/cat/Advance3.png"
import CP25 from "../../src/resources/img/cat/Ziwi3.png"
import CP26 from "../../src/resources/img/cat/RoyalCanin3.png"




export const CatVarietyList = [
    {name: 'Natural Food', count: 1, key: 0},
    {name: 'Freeze and Air Dried', count: 2, key: 1},
    {name: 'Premium', count: 3, key: 2}
]

export const CatFeatureList = [
    {name: 'Australian Made', count: 1, key: 0},
    {name: 'Grain Free', count: 2, key: 1},
    {name: 'Human Grade', count: 3, key: 2},
    {name: 'Hypoallergenic', count: 4, key: 3},
    {name: 'Limited Ingredients', count: 5, key: 4},
    {name: 'Natural', count: 6, key: 7},
    {name: 'Superfood', count: 7, key: 8},
//Type
]

export const ProteinList = [
    {name: 'Chicken', count: 1, key: 0},
    {name: 'Beef', count: 2, key: 1},
    {name: 'Kangaroo', count: 3, key: 2},
    {name: 'Turkey', count: 4, key: 3},
    {name: 'Vension', count: 5, key: 4},
    {name: 'Salmon', count: 6, key: 5},
    {name: 'Fish', count: 7, key: 6},
    {name: 'Lamb', count: 8, key: 7},
//Flavour
]


export const CatBrandList = [
    {name: 'Advance', count: 1, key: 0},
    {name: 'Applaws', count: 2, key: 1},
    {name: 'Black Hawk', count: 3, key: 2},
    {name: 'Hills Science Diet', count: 4, key: 3},
    {name: 'Pro Plan', count: 5, key: 4},
    {name: 'Purina One', count: 6, key: 5},
    {name: 'Royal Canin', count: 7, key: 6},
    {name: 'Vetalogica', count: 8, key: 7},
    {name: 'Ziwi', count: 9, key: 8},
]


export const CatProductList = [
    {
        Product:1,
        source: CP1,
        title: 'ADVANCE',
        subTitle: 'Adult Dry Cat Food Chicken With Rice, 20KG',
        star: 5,
        review: 83,
        mount: '3kg',
        mount2: '12kg',
        price: 139.65,
        state: 'none',
        variety : 'Premium',
        brand : 'Advance',
        Feature : 'Australian Made',
        ProteinSource : 'Chicken'
    },
    {
        Product:2,
        source: CP2,
        title: 'BLACK HWAK',
        subTitle: 'Dry Cat Food Adult Chicken And Rice, 15KG',
        star: 5,
        review: 138,
        mount: '1.5kg',
        mount2: '3kg',
        price: 108.00,
        state: 'none',
        variety : 'Premium',
        brand : 'Black Hwak',
        Feature : 'Australian Made',
        ProteinSource : 'Chicken'
    },
    {
        Product:3,
        source: CP3,
        title: 'FELINE NATURAL',
        subTitle: 'Beef And Hoki Freeze Dried Cat Food, 320G',
        star: 5,
        review: 11,
        mount: '320g',
        price: 30.40,
        state: 'none',
        variety : 'Freeze and Air Dried',
        brand : 'Feline Natural',
        Feature : 'Grain Free',
        ProteinSource : 'Beef'
    },
    {
        Product:4,
        source: CP4,
        title: 'HEALTHY EVERYDAY PETS',
        subTitle: 'Dry Cat Food Adult Poultry, 7KG',
        star: 4,
        review: 49,
        mount: '3kg',
        mount2: '7kg',
        price: 47.50,
        state: 'none',
        variety : 'Premium',
        brand : 'Healthy Everyday Pets',
        Feature : 'Australian Made',
        ProteinSource : 'Chicken'
    },
    {
        Product:5,
        source: CP5,
        title: 'HILLS SCIENCE DIET',
        subTitle: 'Senior 7 Plus Hairball Control Dry Cat Food, 4KG',
        star: 5,
        review: 25,
        mount: '2kg',
        mount2: '4kg',
        price: 53.59,
        state: 'none',
        variety : 'Premium',
        brand : 'Hills Science Diet',
        Feature : 'Grain Free',
        ProteinSource : 'Chicken'
    },
    {
        Product:6,
        source: CP6,
        title: 'IVORY COAT',
        subTitle: 'Dry Cat Food Chicken And Kangaroo, 6KG',
        star: 5,
        review: 1,
        mount: '6kg',
        price: 108.00,
        state: 'none',
        variety : ['Premium','Natural Food'],
        brand : 'Ivory Coat',
        Feature : 'Australian Made',
        ProteinSource : 'Kangaroo'
    },
    {
        Product:7,
        source: CP7,
        title: 'Meals For Meows',
        subTitle: 'Dry Cat Food Adult Kangaroo And Turkey, 20KG',
        star: 4,
        review: 26,
        mount: '2.5kg',
        mount2: '9kg',
        price: 34.56,
        state: 'none',
        variety : 'Natural Food',
        brand : 'Black Hwak',
        Feature : 'Superfood',
        ProteinSource : 'Kangaroo'
    },
    {
        Product:8,
        source: CP8,
        title: 'OPEN FARM',
        subTitle: 'Homestead Turkey And Chicken Cat Dry Food, 3.6KG',
        star: 5,
        review: 19,
        mount: '3.6kg',
        mount2: '7.2kg',
        price: 63.00,
        state: 'none',
        variety : ['Premium','Natural Food'],
        brand : 'Open Farm',
        Feature : 'Human Grade',
        ProteinSource : ['Chicken','Turkey'],
    },
    {
        Product:9,
        source: CP9,
        title: 'ORIJEN',
        subTitle: 'Biologically Appropriate Cat And Kitten Dry Cat Food, 5.45KG',
        star: 5,
        review: 11,
        mount: '1.8kg',
        mount2: '5.45kg',
        price: 59.95,
        state: 'none',
        variety : 'Premium',
        brand : 'Orijen',
        Feature : 'Natural',
        ProteinSource : 'Chicken'
    },
    {
        Product:10,
        source: CP10,
        title: 'PRO PLAN',
        subTitle: 'Adult Chicken Dry Cat Food, 7KG',
        star: 5,
        review: 2,
        mount: '3kg',
        mount2: '7kg',
        price: 33.25,
        state: 'none',
        variety : 'Premium',
        brand : 'Pro Plan',
        Feature : 'Australian Made',
        ProteinSource : 'Chicken'
    },
    {
        Product:11,
        source: CP11,
        title: 'ROYAL CANIN',
        subTitle: 'Indoor Adult Dry Cat Food, 10KG',
        star: 5,
        review: 89,
        mount: '2kg',
        mount2: '4kg',
        price: 32.34,
        state: 'none',
        variety : 'Premium',
        brand : 'Royal Canin',
        Feature : 'Grain Free',
        ProteinSource : 'Chicken'
    },
    {
        Product:12,
        source: CP12,
        title: 'TASTE OF THE WILD',
        subTitle: 'Rocky Mountain Venison Salmon, 6.6KG',
        star: 4,
        review: 36,
        mount: '2kg',
        mount2: '6.6kg',
        price: 27.99,
        state: 'none',
        variety : ['Premium','Natural Food'],
        brand : 'Taste Of The Wild',
        Feature : 'Human Grade',
        ProteinSource : 'Venison'
    },
    {
        Product:13,
        source: CP13,
        title: 'VETALOGICA',
        subTitle: 'Biologically Appropriate Adult Hunter Valley Harvest Dry Cat Food, 3KG',
        star: 4,
        review: 7,
        mount: '3kg',
        mount2: '6kg',
        price: 108.00,
        state: 'none',
        variety : 'Premium',
        brand : 'Black Hwak',
        Feature : 'Australian Made',
        ProteinSource : 'Chicken'
    },
    {
        Product:14,
        source: CP14,
        title: 'WELLNESS',
        subTitle: 'Core Grain Free Indoor Chicken Dry Cat Food, 4.99KG',
        star: 5,
        review: 15,
        mount: '2.27kg',
        mount2: '4.99kg',
        price: 45.60,
        state: 'Sold Out',
        variety : ['Premium','Natural Food'],
        brand : 'Wellness',
        Feature : 'Grain Free',
        ProteinSource : 'Chicken'
    },
    {
        Product:15,
        source: CP15,
        title: 'WHISKAS',
        subTitle: 'Adult 1 Plus Year Beef And Lamb Dry Cat Food, 12KG',
        star: 5,
        review: 3,
        mount: '12kg',
        price: 51.84,
        state: 'none',
        variety : 'Premium',
        brand : 'Whiskas',
        Feature : 'Australian Made',
        ProteinSource : 'Beef'
    },
    {
        Product:16,
        source: CP16,
        title: 'ZIWI',
        subTitle: 'Peak Air Dried Chicken Cat Food, 1KG',
        star: 4,
        review: 5,
        mount: '400g',
        mount2: '1kg',
        price: 67.99,
        state: 'none',
        variety : 'Freeze and Air Dried',
        brand : 'Ziwi',
        Feature : 'Human Grade',
        ProteinSource : 'Chicken'
    },
    {
        Product:17,
        source: CP17,
        title: 'ADVANCE',
        subTitle: 'Multi Cat Dry Cat Food Salmon And Chicken With Rice, 20KG',
        star: 5,
        review: 71,
        mount: '3kg',
        mount2: '6kg',
        price: 31.99,
        state: 'none',
        variety : 'Premium',
        brand : 'Advance',
        Feature : 'Australian Made',
        ProteinSource : ['Beef','Salmon'],
    },
    {
        Product:18,
        source: CP18,
        title: 'HEALTHY EVERYDAY PETS',
        subTitle: 'Dry Cat Food Adult Seafood, 7KG',
        star: 4,
        review: 17,
        mount: '3kg',
        mount2: '7kg',
        price: 47.50,
        state: 'none',
        variety : 'Premium',
        brand : 'Healthy Everyday Pets',
        Feature : 'Australian Made',
        ProteinSource : 'Fish',
    },
    {
        Product:19,
        source: CP19,
        title: 'HILLS SCIENCE DIET',
        subTitle: 'Kitten Dry Cat Food, 4KG',
        star: 5,
        review: 53,
        mount: '1.58kg',
        mount2: '4kg',
        price: 26.12,
        state: 'none',
        variety : 'Premium',
        brand : 'Hills Science Diet',
        Feature : 'Human Grade',
        ProteinSource : 'Chicken',
    },
    {
        Product:20,
        source: CP20,
        title: 'MEALS FOR MEOWS',
        subTitle: 'Grain Free Dry Cat Food Adult Mackerel And Salmon, 20KG',
        star: 4,
        review: 28,
        mount: '2.5kg',
        mount2: '9kg',
        price: 29.75,
        state: 'none',
        variety : 'Premium',
        brand : 'Meals For Meows',
        Feature : 'Australian Made',
        ProteinSource : 'Salmon',
    },
    {
        Product:21,
        source: CP21,
        title: 'ORIJEN',
        subTitle: 'Biologically Appropriate Six Fish Dry Cat Food, 5.45KG',
        star: 5,
        review: 71,
        mount: '1.8kg',
        mount2: '5.45kg',
        price: 64.95,
        state: 'none',
        variety : 'Natural Food',
        brand : 'Orijen',
        Feature : 'Human Grade',
        ProteinSource : 'Fish',
    },
    {
        Product:22,
        source: CP22,
        title: 'ROYAL CANIN',
        subTitle: 'Persian Adult Dry Cat Food, 10KG',
        star: 5,
        review: 10,
        mount: '2kg',
        mount2: '4kg',
        price: 33.13,
        state: 'none',
        variety : 'Premium',
        brand : 'Royal Canin',
        Feature : 'Grain Free',
        ProteinSource : 'Chicken',
    },
    {
        Product:23,
        source: CP23,
        title: 'ZIWI',
        subTitle: 'Peak Dry Cat Food Mackerel And Lamb, 1KG',
        star: 5,
        review: 5,
        mount: '400g',
        mount2: '1kg',
        price: 72.24,
        state: 'none',
        variety : 'Premium',
        brand : 'Ziwi',
        Feature : 'Human Grade',
        ProteinSource : 'Fish',
    },
    {
        Product:24,
        source: CP24,
        title: 'ADVANCE',
        subTitle: 'Kitten Dry Cat Food Chicken With Rice, 20KG',
        star: 5,
        review: 77,
        mount: '3kg',
        mount2: '6kg',
        price: 34.40,
        state: 'none',
        variety : 'Premium',
        brand : 'Advace',
        Feature : 'Australian Made',
        ProteinSource : 'Chicken',
    },
    {
        Product:25,
        source: CP24,
        title: 'ADVANCE',
        subTitle: 'Kitten Dry Cat Food Chicken With Rice, 20KG',
        star: 5,
        review: 77,
        mount: '3kg',
        mount2: '6kg',
        price: 34.40,
        state: 'none',
        variety : 'Premium',
        brand : 'Advace',
        Feature : 'Australian Made',
        ProteinSource : 'Chicken',
    },
    {
        Product:26,
        source: CP25,
        title: 'ZIWI',
        subTitle: 'Peak Dry Cat Food Lamb, 1KG',
        star: 4,
        review: 10,
        mount: '400g',
        mount2: '1kg',
        price: 35.19,
        state: 'none',
        variety : 'Freeze and Air Dried',
        brand : 'Advace',
        Feature : 'Human Grade',
        ProteinSource : 'Lamb',
    },
    {
        product:27,
        source: CP26,
        title: 'ROYAL CANIN',
        subTitle: 'Kitten Dry Cat Food, 10KG',
        star: 5,
        review: 73,
        mount: '2kg',
        mount2: '4kg',
        price: 31.50,
        state: 'none',
        variety : 'Premium',
        brand : 'Royal Canin',
        Feature : 'Human Grade',
        ProteinSource : 'Chicken',
    },
    ]
