import OP1 from "../../src/resources/img/other/api-bottom-feeder-shrimp-pellets,43g.png"
import OP2 from "../../src/resources/img/other/fluval-colour-enhancing-medium-sinking-pellets,150g.png"
import OP3 from "../../src/resources/img/other/hikari-cichlid-gold-sinking-mini,342g.png"
import OP4 from "../../src/resources/img/other/hikari-economy-medium,4kg.png"
import OP5 from "../../src/resources/img/other/nutrafin-max-goldfish-flakes,19g.png"
import OP6 from "../../src/resources/img/other/ocean-free-kirameki-premium-economy-koi-pond-pellet-large,1kg.png"
import OP7 from "../../src/resources/img/other/pisces-laboratories-algae-wafers,95g.png"
import OP8 from "../../src/resources/img/other/saikoh-basic-goldfish-and-koi-pellet-large,5kg.png"
import OP9 from "../../src/resources/img/other/tetra-cichlid-crisps-fish-food,93g.png"
import OP10 from "../../src/resources/img/other/tetramin-goldfish-flakes-fish-food,12g.png"
import OP11 from "../../src/resources/img/other/api-tropical-flake-food,31g.png"
import OP12 from "../../src/resources/img/other/tetramin-tropical-granules-fish-food,34g.png"
import OP13 from "../../src/resources/img/other/tetra-pro-plecowafers-algae-eaters-complete-diet-fish-food,86g.png"
import OP14 from "../../src/resources/img/other/saikoh-basic-goldfish-and-koi-pellet-medium,1kg.png"
import OP15 from "../../src/resources/img/other/tetra-fresh-delica-brine-shrimp,48g.png"
import OP16 from "../../src/resources/img/other/hikari-gold-small,500g.png"
import OP17 from "../../src/resources/img/other/nutrafin-max-medium-goldfish-sinking-pellets,210g.png"
import OP18 from "../../src/resources/img/other/tetra-pro-tropical-crisps-fish-food,32g.png"
import OP19 from "../../src/resources/img/other/ocean-free-pro-marine-fish-pellets,60g.png"
import OP20 from "../../src/resources/img/other/fluval-goldfish-medium-sinking-pellets,150g.png"
import OP21 from "../../src/resources/img/other/nutrafin-max-pleco-logs,95g.png"
import OP22 from "../../src/resources/img/other/saikoh-basic-goldfish-and-koi-pellet-mini,1kg.png"
import OP23 from "../../src/resources/img/other/tetra-pro-tropical-colour-crisps,75g.png"
import OP24 from "../../src/resources/img/other/tetra-shrimp-wafers-catfish-loaches-complete-diet-fish-food,86g.png"
import OP25 from "../../src/resources/img/other/saikoh-colour-goldfish-and-koi-pellet-medium,500g.png"
import OP26 from "../../src/resources/img/other/api-algae-eater-wafers,37g.png"
import OP27 from "../../src/resources/img/other/tetra-pro-plecowafers-extreme-algae-eaters-complete-diet-fish-food,60g.png"
import OP28 from "../../src/resources/img/other/tetramin-tropical-flakes-fish-food,12g.png"
import OP29 from "../../src/resources/img/other/fluval-goldfish-flakes,32g.png"








export const OtherVarietyList = [
    {name: 'Betta Food', count: 1, key: 0},
    {name: 'Bottom Feeders and Algae Eaters', count: 2, key: 1},
    {name: 'Cichild Food', count: 3, key: 2},
    {name: 'Goldfish Food', count: 4, key: 3},
    {name: 'Holiday Food', count: 5, key: 4},
    {name: 'Marine Food', count: 6, key: 5},
    {name: 'Other Fish Food', count: 7, key: 6},
    {name: 'Tropical Food', count: 8, key: 7},
    {name: 'Turtle Food', count: 9, key: 8},
    {name: 'Koi and Pond Fish Food', count: 10, key: 9},
]

export const OtherTypeList = [
    {name: 'Bloodworms', count: 1, key: 0},
    {name: 'Crisps', count: 2, key: 1},
    {name: 'Flakes', count: 3, key: 2},
    {name: 'Granules', count: 4, key: 3},
    {name: 'Pellets', count: 5, key: 4},
    {name: 'Shrimp', count: 6, key: 7},
    {name: 'Sticks', count: 7, key: 8},
    {name: 'Wafers', count: 8, key: 9},
//Type
]

export const OtherBreedList = [
    {name: 'Betta', count: 1, key: 0},
    {name: 'Cichlid', count: 2, key: 1},
    {name: 'Discus', count: 3, key: 2},
    {name: 'Frog', count: 4, key: 3},
    {name: 'Goldfish', count: 5, key: 4},
    {name: 'Koi', count: 6, key: 5},
    {name: 'Marine Fish', count: 7, key: 6},
    {name: 'Tropical Fish', count: 8, key: 7},
//Feature
]


export const OtherBrandList = [
    {name: 'Api', count: 1, key: 0},
    {name: 'Fluval', count: 2, key: 1},
    {name: 'Hikari', count: 3, key: 2},
    {name: 'Nutrafin', count: 4, key: 3},
    {name: 'Ocean', count: 5, key: 4},
    {name: 'Saikoh', count: 6, key: 5},
    {name: 'Pisces', count: 7, key: 6},
    {name: 'Tetra', count: 8, key: 7},
    {name: 'Tetramin', count: 9, key: 8},
]


export const OtherProductList = [
    {
        Product:1,
        source: OP1,
        title: 'API',
        subTitle: 'Bottom Feeder Shrimp Pellets,43g',
        star: 5,
        review: 23,
        mount: '43g',
        mount2: '100g',
        price: 10.65,
        state: 'none',
        variety : 'Betta Food',
        type : 'Bloodworms',
        Breed : 'Betta',
        brand : 'Api',
    },
    {
        Product:2,
        source: OP2,
        title: 'FLUVAL',
        subTitle: 'Colour Enhancing Medium Sinking Pellets,150g',
        star: 5,
        review: 138,
        mount: '150g',
        mount2: '300g',
        price: 15.00,
        state: 'none',
        variety : 'Bottom Feeders and Algae Eaters',
        type : 'Crisps',
        Breed : 'Cichlid',
        brand : 'Fluval',

    },
    {
        Product:3,
        source: OP3,
        title: 'HIKARI',
        subTitle: 'Cichlid Gold Sinking Mini,342g',
        star: 5,
        review: 11,
        mount: '342g',
        price: 9.40,
        state: 'none',
        variety : 'Cichild Food',
        type : 'Flakes',
        Breed : 'Discus',
        brand : 'Hikari',

    },
    {
        Product:4,
        source: OP4,
        title: 'HIKARI',
        subTitle: 'Economy Medium,4kg',
        star: 2,
        review: 27,
        mount: '4kg',
        mount2: '10kg',
        price: 37.50,
        state: 'none',
        variety : 'Goldfish Food',
        type : 'Pellets',
        Breed : 'Koi',
        brand : 'Hikari',

    },
    {
        Product:5,
        source: OP5,
        title: 'NUTRAFIN',
        subTitle: 'Max Goldfish Flakes,19g',
        star: 5,
        review: 25,
        mount: '19g',
        mount2: '100g',
        price: 5.59,
        state: 'none',
        variety : 'Other Fish Food',
        type : 'Sticks',
        Breed : 'Tropical Fish',
        brand : 'Nutrafin',

    },
    {
        Product:6,
        source: OP6,
        title: 'OCEAN',
        subTitle: 'Free Kirameki Premium Economy Koi Pond Pellet Large,1kg',
        star: 3,
        review: 1,
        mount: '1kg',
        price: 38.85,
        state: 'none',
        variety : 'Marine Food',
        type : 'Shrimp',
        Breed : 'Marine Fish',
        brand : 'Ocean',

    },
    {
        Product:7,
        source: OP7,
        title: 'PISCES',
        subTitle: 'Laboratories Algae Wafers,95g',
        star: 4,
        review: 26,
        mount: '95g',
        mount2: '200g',
        price: 14.56,
        state: 'none',
        variety : 'Koi and Pond Fish Food',
        type : 'Sticks',
        Breed : 'Discus',
        brand : 'Pisces',

    },
    {
        Product:8,
        source: OP8,
        title: 'SAIKOH',
        subTitle: 'Basic Goldfish And Koi Pellet Large,5kg',
        star: 5,
        review: 19,
        mount: '5kg',
        mount2: '8kg',
        price: 33.00,
        state: 'none',
        variety : 'Turtle Food',
        type : 'Flakes',
        Breed : 'Betta',
        brand : 'Saikoh',

    },
    {
        Product:9,
        source: OP9,
        title: 'TETRA',
        subTitle: 'Cichlid Crisps Fish Food,93g',
        star: 2,
        review: 1,
        mount: '93g',
        mount2: '500g',
        price: 19.95,
        state: 'none',
        variety : 'Turtle Food',
        type : 'Pellets',
        Breed : 'Discus',
        brand : 'Tetra',

    },
    {
        Product:10,
        source: OP10,
        title: 'TETRAMIN',
        subTitle: 'Goldfish Flakes Fish Food,12g',
        star: 4,
        review: 2,
        mount: '12g',
        mount2: '25g',
        price: 3.25,
        state: 'none',
        variety : 'Cichild Food',
        type : 'Wafers',
        Breed : 'Marine Fish',
        brand : 'Tetramin',

    },
    {
        Product:11,
        source: OP11,
        title: 'API',
        subTitle: 'Tropical Flake Food,31g',
        star: 5,
        review: 89,
        mount: '31g',
        mount2: '100g',
        price: 12.34,
        state: 'none',
        variety : 'Holiday Food',
        type : 'Sticks',
        Breed : 'Cichlid',
        brand : 'Api',

    },
    {
        Product:12,
        source: OP12,
        title: 'TETRAMIN',
        subTitle: 'Tropical Granules Fish Food,34g',
        star: 4,
        review: 36,
        mount: '34g',
        mount2: '150g',
        price: 11.99,
        state: 'none',
        variety : 'Tropical Food',
        type : 'Flakes',
        Breed : 'Betta',
        brand : 'Tetramin',

    },
    {
        Product:13,
        source: OP13,
        title: 'TETRA',
        subTitle: 'Pro Plecowafers Algae Eaters Complete Diet Fish Food,86g',
        star: 4,
        review: 7,
        mount: '86g',
        mount2: '500g',
        price: 8.95,
        state: 'none',
        variety : 'Betta Food',
        type : 'Bloodworms',
        Breed : 'Discus',
        brand : 'Tetra',

    },
    {
        Product:14,
        source: OP14,
        title: 'SAIKOH',
        subTitle: 'Basic Goldfish And Koi Pellet Medium,1kg',
        star: 5,
        review: 15,
        mount: '1kg',
        mount2: '3kg',
        price: 27.60,
        state: 'Sold Out',
        variety : 'Tropical Food',
        type : 'Pellets',
        Breed : 'Cichlid',
        brand : 'Saikoh',

    },
    {
        Product:15,
        source: OP15,
        title: 'TETRA',
        subTitle: 'Fresh Delica Brine Shrimp,48g',
        star: 5,
        review: 3,
        mount: '48g',
        price: 7.84,
        state: 'none',
        variety : 'Koi and Pond Fish Food',
        type : 'Flakes',
        Breed : 'Frog',
        brand : 'Tetra',

    },
    {
        Product:16,
        source: OP16,
        title: 'HIKARI',
        subTitle: 'Gold Small,500g',
        star: 3,
        review: 5,
        mount: '500g',
        mount2: '1kg',
        price: 17.99,
        state: 'none',
        variety : 'Marine Food',
        type : 'Bloodworms',
        Breed : 'Cichlid',
        brand : 'Hikari',

    },
    {
        Product:17,
        source: OP17,
        title: 'NUTRAFIN',
        subTitle: 'Max Medium Goldfish Sinking Pellets,210g',
        star: 5,
        review: 71,
        mount: '210g',
        mount2: '500g',
        price: 11.99,
        state: 'none',
        variety : 'Marine Food',
        type : 'Wafers',
        Breed : 'Betta',
        brand : 'Nutrafin',

    },
    {
        Product:18,
        source: OP18,
        title: 'TETRA',
        subTitle: 'Pro- Tropical Crisps Fish Food,32g',
        star: 4,
        review: 17,
        mount: '32g',
        mount2: '150g',
        price: 7.50,
        state: 'none',
        variety : 'Bottom Feeders and Algae Eaters',
        type : 'Crisps',
        Breed : 'Goldfish',
        brand : 'Tetra',
    },
    {
        Product:19,
        source: OP19,
        title: 'OCEAN',
        subTitle: 'Free Pro Marine Fish Pellets,60g',
        star: 5,
        review: 53,
        mount: '60g',
        mount2: '150g',
        price: 6.12,
        state: 'none',
        variety : 'Turtle Food',
        type : 'Pellets',
        Breed : 'Koi',
        brand : 'Ocean',

    },
    {
        Product:20,
        source: OP20,
        title: 'FLUVAL',
        subTitle: 'Goldfish Medium Sinking Pellets,150g',
        star: 4,
        review: 28,
        mount: '150g',
        mount2: '500g',
        price: 19.75,
        state: 'none',
        variety : 'Goldfish Food',
        type : 'Bloodworms',
        Breed : 'Goldfish',
        brand : 'Fluval',

    },
    {
        Product:21,
        source: OP21,
        title: 'NUTRAFIN',
        subTitle: 'Max Pleco Logs,95g',
        star: 5,
        review: 71,
        mount: '95g',
        mount2: '300g',
        price: 14.95,
        state: 'none',
        variety : 'Tropical Food',
        type : 'Sticks',
        Breed : 'Cichlid',
        brand : 'Nutrafin',

    },
    {
        Product:22,
        source: OP22,
        title: 'SAIKOH',
        subTitle: 'Basic- Goldfish And Koi Pellet Mini,1kg',
        star: 5,
        review: 10,
        mount: '1kg',
        mount2: '2.5kg',
        price: 23.13,
        state: 'none',
        variety : 'Holiday Food',
        type : 'Shrimp',
        Breed : 'Discus',
        brand : 'Saikoh',

    },
    {
        Product:23,
        source: OP23,
        title: 'TETRA',
        subTitle: 'Pro Tropical Colour Crisps,75g',
        star: 5,
        review: 5,
        mount: '75g',
        mount2: '1kg',
        price: 12.24,
        state: 'none',
        variety : 'Other Fish Food',
        type : 'Sticks',
        Breed : 'Discus',
        brand : 'Tetra',

    },
    {
        Product:24,
        source: OP24,
        title: 'TETRA',
        subTitle: 'Shrimp Wafers Catfish Loaches Complete Diet Fish Food,86g',
        star: 5,
        review: 77,
        mount: '86g',
        mount2: '500g',
        price: 24.40,
        state: 'none',
        variety : 'Tropical Food',
        type : 'Wafers',
        Breed : 'Marine Fish',
        brand : 'Tetra',

    },
    {
        Product:25,
        source: OP25,
        title: 'SAIKOH',
        subTitle: 'Colour Goldfish And Koi Pellet Medium,500g',
        star: 5,
        review: 77,
        mount: '500g',
        mount2: '2kg',
        price: 34.40,
        state: 'none',
        variety : 'Betta Food',
        type : 'Crisps',
        Breed : 'Frog',
        brand : 'Saikoh',

    },
    {
        Product:26,
        source: OP26,
        title: 'API',
        subTitle: 'Algae Eater Wafers,37g',
        star: 4,
        review: 10,
        mount: '37g',
        mount2: '300g',
        price: 5.19,
        state: 'none',
        variety : 'Tropical Food',
        type : 'Sticks',
        Breed : 'Koi',
        brand : 'Api',

    },
    {
        product:27,
        source: OP27,
        title: 'TETRA',
        subTitle: 'Pro Plecowafers Extreme Algae Eaters Complete Diet Fish Food,60g',
        star: 5,
        review: 73,
        mount: '68g',
        mount2: '250g',
        price: 11.50,
        state: 'none',
        variety : 'Other Fish Food',
        type : 'Wafers',
        Breed : 'Cichlid',
        brand : 'Tetra',

    },
    {
        product:28,
        source: OP28,
        title: 'TETRAMIN',
        subTitle: 'Tropical Flakes Fish Food,12g',
        star: 5,
        review: 73,
        mount: '12g',
        mount2: '150g',
        price: 11.50,
        state: 'none',
        variety : 'Other Fish Food',
        type : 'Wafers',
        Breed : 'Frog',
        brand : 'Tetramin',

    },
    {
        product:29,
        source: OP29,
        title: 'FLUVAL',
        subTitle: 'Goldfish Flakes,32g',
        star: 5,
        review: 73,
        mount: '68g',
        mount2: '250g',
        price: 11.50,
        state: 'none',
        variety : 'Goldfish Food',
        type : 'Sticks',
        Breed : 'Discus',
        brand : 'Fluval',

    },
]
